[template]
src = "allowed-external-content.txt.tmpl"
dest = "/opt/tomcat/webapps/fcrepo/WEB-INF/classes/config/allowed-external-content.txt"
uid = 100
gid = 1000
mode = "0640"
keys = [ "/allow/external" ]
