name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - "**/README.md"
      - "**/README.dockerhub.md"
      - ".github/workflows/dockerhub-description.yml"
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fix Relative Paths
        run: |
          find . -maxdepth 2 -mindepth 2 -type f -name "README*.md" -exec sed -i 's/](\.\.\/\([^/]*\).*)/](.\/\1)/g' {} \;

      - name: ActiveMQ - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/activemq
          readme-filepath: ./activemq/README.md

      - name: Alpaca - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/alpaca
          readme-filepath: ./alpaca/README.md

      - name: Base - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/base
          readme-filepath: ./base/README.md

      - name: Blazegraph - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/blazegraph
          readme-filepath: ./blazegraph/README.md

      - name: cantaloupe - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/cantaloupe
          readme-filepath: ./cantaloupe/README.dockerhub.md

      - name: Code-Server - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/code-server
          readme-filepath: ./code-server/README.md

      - name: Composer - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/composer
          readme-filepath: ./composer/README.md

      - name: Crayfish - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/crayfish
          readme-filepath: ./crayfish/README.md

      - name: CrayFits - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/crayfits
          readme-filepath: ./crayfits/README.md

      - name: Drupal - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/drupal
          readme-filepath: ./drupal/README.md

      - name: Fcrepo6 - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/fcrepo6
          readme-filepath: ./fcrepo6/README.md

      - name: Fits - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/fits
          readme-filepath: ./fits/README.md

      - name: Handle - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/handle
          readme-filepath: ./handle/README.md

      - name: Homarus - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/homarus
          readme-filepath: ./homarus/README.md

      - name: Houdini - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/houdini
          readme-filepath: ./houdini/README.md

      - name: hypercube - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/hypercube
          readme-filepath: ./hypercube/README.md

      - name: Java - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/java
          readme-filepath: ./java/README.md

      - name: MariaDB - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/mariadb
          readme-filepath: ./mariadb/README.md

      - name: Matomo - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/matomo
          readme-filepath: ./matomo/README.md

      - name: Milliner - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/milliner
          readme-filepath: ./milliner/README.md

      - name: Nginx - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/nginx
          readme-filepath: ./nginx/README.md

      - name: PostgreSQL - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/postgresql
          readme-filepath: ./postgresql/README.md

      - name: RipRap - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/riprap
          readme-filepath: ./riprap/README.md

      - name: Solr - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/solr
          readme-filepath: ./solr/README.md

      - name: Test - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/tomcat
          readme-filepath: ./test/README.md

      - name: Tomcat - Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.REGISTRY_DOCKERHUB_USER }}
          password: ${{ secrets.REGISTRY_DOCKERHUB_TOKEN }}
          repository: ${{ secrets.REGISTRY_DOCKERHUB }}/tomcat
          readme-filepath: ./tomcat/README.md
