name: run renovate

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '15 10 * * *'

jobs:
  run:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: run renovate
        env:
          BASE_BRANCH: ${{ github.event_name == 'schedule' && 'main' || github.ref_name }}
        run: |
          # fetch GitHub App token for this repo
          echo "${{ secrets.GH_APP_PRIV_KEY }}" | base64 -d > private-key.pem
          export RENOVATE_TOKEN=$(./ci/fetch-app-token.sh ${{ secrets.GH_APP_ID }} ${{ secrets.GH_APP_INSTALLATION_ID }} private-key.pem)
          echo "::add-mask::$RENOVATE_TOKEN"

          # run renovate with our token
          # using branch set in workflow dispatch to allow testing PRs
          # see https://docs.renovatebot.com/configuration-options/#basebranches
          export RENOVATE_BASE_BRANCHES=$(jq -c -n --arg branch "$BASE_BRANCH" '[$branch]')
          echo "Running renovate against ${RENOVATE_BASE_BRANCHES}"
          docker run \
            --env LOG_LEVEL=debug \
            --env RENOVATE_ALLOWED_COMMANDS='["^bash ci/update-sha.sh .*$"]' \
            --env RENOVATE_PLATFORM=github \
            --env RENOVATE_REPOSITORIES=islandora-devops/isle-buildkit \
            --env RENOVATE_BASE_BRANCHES \
            --env RENOVATE_TOKEN \
            --rm \
            -v $(pwd):/usr/src/app \
            renovate/renovate
